#ifndef UART_COMMANDS_H
#define UART_COMMANDS_H

//-- BLUETHOOT UART COMMANDS -- //

#define BT_COMMAND_REQ_SCAN        "SCAN"
#define BT_COMMAND_RES_SCAN_START  "SCAN:START"
#define BT_COMMAND_RES_SCAN_DONE   "SCAN:DONE"
#define BT_COMMAND_RES_SCAN_DEVICE "SCAN:DEVICE"
#define BT_COMMAND_RES_SCAN_UPDATE "SCAN:UPDATE"

//-- CONNECT -- //
#define BT_COMMAND_REQ_CONNECT          "CONNECT"
#define BT_COMMAND_RES_CONNECT_START    "CONNECT:START"
#define BT_COMMAND_RES_CONNECT_OK       "CONNECT:OK"
#define BT_COMMAND_RES_CONNECT_FAIL     "CONNECT:FAIL"
#define BT_COMMAND_RES_CONNECT_LOST     "CONNECT:LOST"
#define BT_COMMAND_RES_CONNECT_ERROR    "CONNECT:ERROR"

#define BT_COMMAND_REQ_DISCONNECT       "DISCONNECT"
#define BT_COMMAND_RES_DISCONNECT_OK    "DISCONNECT:OK"

//-- DISCOVER -- //
#define BT_COMMAND_REQ_DISCOVER         "DISCOVER"
#define BT_COMMAND_RES_DISCOVER_START   "DISCOVER:START"
#define BT_COMMAND_RES_DISCOVER_SERVICE "DISCOVER:SERVICE"
#define BT_COMMAND_RES_DISCOVER_CHAR    "DISCOVER:CHAR"
#define BT_COMMAND_RES_DISCOVER_DESC    "DISCOVER:DESC"
#define BT_COMMAND_RES_DISCOVER_DONE    "DISCOVER:DONE"
#define BT_COMMAND_RES_DISCOVER_FAIL    "DISCOVER:FAIL"

//-- SUB GHZ UART COMMANDS -- //

#define SUBGHZ_COMMAND_REQ_CHECK_MODULE     "SUBGHZ_CHECK_MODULE"
#define SUBGHZ_COMMAND_RES_CHECK_MODULE     "SUBGHZ_CHECK_MODULE_RES"
#define SUBGHZ_COMMAND_REQ_SET_FRECUENCY    "SUBGHZ_SET_FRECUENCY"
#define SUBGHZ_COMMAND_RES_SET_FRECUENCY    "SUBGHZ_SET_FRECUENCY_RES"
#define SUBGHZ_COMMAND_REQ_CAPTURE          "SUBGHZ_CAPTURE"
#define SUBGHZ_COMMAND_RES_CAPTURE_START    "SUBGHZ_CAPTURE:START"
#define SUBGHZ_COMMAND_RES_CAPTURE_DATA     "SUBGHZ_CAPTURE:DATA"
#define SUBGHZ_COMMAND_RES_CAPTURE_DONE     "SUBGHZ_CAPTURE:SUCCESS"
#define SUBGHZ_COMMAND_RES_CAPTURE_FAIL     "SUBGHZ_CAPTURE:FAIL"
#define SUBGHZ_COMMAND_RES_CAPTURE_ERROR    "SUBGHZ_CAPTURE_ERROR"

#endif /* UART_COMMANDS_H */