#ifndef UART_COMMANDS_H
#define UART_COMMANDS_H

//-- UART COMMANDS -- //

#define BT_COMMAND_REQ_SCANN        "SCAN"
#define BT_COMMAND_RES_SCANN_START  "SCAN:START"
#define BT_COMMAND_RES_SCANN_DONE   "SCAN:DONE"
#define BT_COMMAND_RES_SCANN_DEVICE "SCAN:DEVICE"
#define BT_COMMAND_RES_SCANN_UPDATE "SCAN:UPDATE"

//-- CONNECT -- //
#define BT_COMMAND_REQ_CONNECT          "CONNECT"
#define BT_COMMAND_RES_CONNECT_START    "CONNECT:START"
#define BT_COMMAND_RES_CONNECT_OK       "CONNECT:OK"
#define BT_COMMAND_RES_CONNECT_FAIL     "CONNECT:FAIL"
#define BT_COMMAND_RES_CONNECT_LOST     "CONNECT:LOST"
#define BT_COMMAND_RES_CONNECT_ERROR    "CONNECT:ERROR"

#define BT_COMMAND_REQ_DISCONNECT       "DISCONNECT"
#define BT_COMMAND_RES_DISCONNECT_OK    "DISCONNECT:OK"

//-- DISCOVER -- //
#define BT_COMMAND_REQ_DISCOVER         "DISCOVER"
#define BT_COMMAND_RES_DISCOVER_START   "DISCOVER:START"
#define BT_COMMAND_RES_DISCOVER_SERVICE "DISCOVER:SERVICE"
#define BT_COMMAND_RES_DISCOVER_CHAR    "DISCOVER:CHAR"
#define BT_COMMAND_RES_DISCOVER_DESC    "DISCOVER:DESC"
#define BT_COMMAND_RES_DISCOVER_DONE    "DISCOVER:DONE"
#define BT_COMMAND_RES_DISCOVER_FAIL    "DISCOVER:FAIL"

#endif /* UART_COMMANDS_H */